version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - db
    depends_on:
      - db
    ports:
    - "127.0.0.1:3000:3000"
    restart: "always"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/usr/src/app
    command: npm run start:dev --prefix /usr/src/app
  db:
    image: postgres:9
    ports:
      - "127.0.0.1:5432:5432"
    restart: "always"
