version: '3'
services:
  app:
    build: .
    links:
      - db
    depends_on:
      - db
    ports:
      - "127.0.0.1:3000:3000"
    restart: "always"
    environment:
      - NODE_ENV=production
  db:
    image: postgres:9
    restart: "always"
